shared:
  adapter: sqlite3
  pool: 5
  timeout: 5000
development:
  database: db/development.sqlite3
  adapter: sqlite3
  pool: 5
  timeout: 5000
test:
  database: db/test.sqlite3
  adapter: sqlite3
  pool: 5
  timeout: 5000
