test:
  require_authentication: false
  num_load_balanced_cdn_urls: 0
  cdn_urls:
  - http://localhost
development:
  require_authentication: false
  num_load_balanced_cdn_urls: 0
  cdn_urls:
  - http://localhost
