default: &default
  version: 6.3.0
  download_dir: <%= Rails.root.join('tmp', 'solr-download') %>
  verbose: false
  managed: true
  solr_options:
    "addlopts" : "-Djetty.host=127.0.0.1"

development:
  <<: *default
  port: 8983
  instance_dir: <%= Rails.root.join('tmp', 'solr-development') %>
  collection:
    - name: 'dcv-dev'
      dir: <%= Rails.root.join('spec', 'fixtures', 'solr_cores', 'dcv-solr-6-3', 'conf') %>

test:
  <<: *default
  port: 8993
  instance_dir: <%= Rails.root.join('tmp', 'solr-test') %>
  collection:
    - name: 'dcv-test'
      dir: <%= Rails.root.join('spec', 'fixtures', 'solr_cores', 'dcv-solr-6-3', 'conf') %>
