name: CI

on:
  push:
    branches: [ '*' ]

jobs:
  ci-rails-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1.7']
        node: ['16']
    env:
      RAILS_ENV: test
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      FONT_AWESOME_TOKEN: ${{ secrets.FONT_AWESOME_TOKEN }}

    steps:
      - name: Install libxslt for nokogiri gem (required for ruby platform build)
        run: sudo apt-get install -y libxml2-dev libxslt-dev
      - uses: actions/checkout@v3
      - name: Add --no-document option to .gemrc file to speed up bundle install
        run: "echo 'gem: --no-document' > ~/.gemrc"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - name: Run CI task
        run: bundle exec rake dcv:ci SHAKAPACKER_RECOMPILE=true
